version: '2'
services:

  streamline.dev:
    build:
        context: ./images/streamline
        dockerfile: Dockerfile
    image: jdye64/streamline-demo:streamline-0.1.0-SNAPSHOT
    networks:
      - dev
    hostname: streamline
    domainname: dev
    ports:
      - "8888:8080"
    links:
      - registry.dev

  registry.dev:
    build:
        context: ./images/registry
        dockerfile: Dockerfile
    image: jdye64/registry-demo:0.3.0-SNAPSHOT
    networks:
      - dev
    hostname: registry
    domainname: dev
    ports:
      - "9090:9090"
    links:
      - mysql.dev

  mysql.dev:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: registry
      MYSQL_DATABASE: registry_db
      MYSQL_USER: registry_user
      MYSQL_PASSWORD: registry_password
    networks:
      - dev
    hostname: mysql
    domainname: dev

networks:
  dev:
    driver: bridge
