version: '2'
services:

  nifi.dev:
    image: jdye64/nifi:1.1.2
    networks:
      - dev
    hostname: nifi
    domainname: dev
    ports:
      - "8787:8080" # Web UI
      - "8788:8181" # Site2Site Port

  streamline.dev:
    build:
        context: ./images/streamline
        dockerfile: Dockerfile
    image: jdye64/streamline-demo:streamline-0.1.0-SNAPSHOT
    networks:
      - dev
    hostname: streamline
    domainname: dev
    ports:
      - "8888:8080"
    links:
      - registry.dev

  registry.dev:
    image: jdye64/registry:0.1.0-SNAPSHOT
    networks:
      - dev
    hostname: registry
    domainname: dev
    ports:
      - "9090:9090"
    links:
      - mysql.dev

  mysql.dev:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: registry
      MYSQL_DATABASE: registry_db
      MYSQL_USER: registry_user
      MYSQL_PASSWORD: registry_password
    networks:
      - dev
    hostname: mysql
    domainname: dev

  postgres.dev:
    build:
        context: ./images/postgres
        dockerfile: Dockerfile
        args:
         - DDL_URL=${DDL_URL}
    image: jdye64/streamline-demo:hdp-postgres-260
    networks:
     - dev
    hostname: postgres
    domainname: dev

  ambari-server.dev:
    build: 
      context: ./images/ambari-server
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
    image: jdye64/streamline-demo:ambari-260
    networks:
     - dev
    hostname: ambari-server
    domainname: dev
    depends_on:
      - "postgres.dev"
    ports:
     - "8080:8080"

  master0.dev:
    build:
      context: ./images/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: jdye64/streamline-demo:hdp-master-260
    privileged: true
    networks:
     - dev
    hostname: master0
    domainname: dev
    depends_on:
      - "ambari-server.dev"
    ports:
     # ZooKeeper
     - "2181:2181"
     # HDFS
     - "8020:8020"
     - "9000:9000"
     - "50090:50090"
     # YARN
     - "8088:8088"
     - "8050:8050"
     - "8025:8025"
     - "8030:8030"
     - "8141:8141"
     - "45454:45454"
     - "10200:10200"
     - "8188:8188"
     - "8190:8190"
     - "19888:19888"
     # HiveServer2
     - "10000:10000"
     - "9999:9999"
     - "9933:9933"
     - "10015:10015"
     # HBase
     - "16000:16000"
     - "16010:16010"
     # Storm
     - "8000:8000"
     - "8744:8744"
     # Oozie
     - "11000:11000"
     - "11443:11443"
     # Knox
     - "8443:8443"
     # Ranger
     - "6080:6080"
     - "6182:6182"
     - "6083:6083"
     - "6183:6183"
     # Grafana
     - "3000:3000"
     # Zeppelin
     - "9995:9995"
     # Kerberos
     #- "88:88"
     # Druid ports
     - "9088:9088"
     - "1527:1527"
     - "8082:8082"
     - "8081:8081"
     - "8083:8083"
     - "8091:8091"
     - "8100:8100"
     - "8090:8090"
     # Druid Router Port. Notice is is not 8888 because that is used by streamline
     - "8889:8888"
    links:
     - dn0.dev

  dn0.dev:
    build:
      context: ./images/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: jdye64/streamline-demo:hdp-worker-260
    privileged: true
    networks:
     - dev
    hostname: dn0
    domainname: dev
    depends_on:
      - "ambari-server.dev"
    ports:
     # HDFS
     - "50070:50070"
     - "50470:50470"
     - "50075:50075"
     - "50475:50475"
     - "50010:50010"
     - "50020:50020"
     - "50030:50030"
     # HBase
     - "16020:16020"
     - "16030:16030"
     # Yarn
     - "45455:45454"
     - "8042:8042"
     # Solr
     - "8983:8983"
     # Kafka
     - "6667:6667"

networks:
  dev:
    driver: bridge
